version: '3.4'

services:
  mtask:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8081:8081"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: MTask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Esculap1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
